sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt update
  - sudo apt install -y r-base r-base-core r-recommended
#  - sudo R CMD javareconf -e
  - sudo Rscript ./setup.R

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    all_branches: true
