sudo: false
dist: trusty
language: java
jdk:
  - openjdk11

cache:
  directories:
  - "$HOME/.cache"
  
env:
  - R_HOME=/usr/lib/R LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$JAVA_HOME/jre/lib:$R_HOME/lib:$R_HOME/bin"

before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml
  - wget --no-check-certificate https://dlcdn.apache.org/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
  - tar xzvf apache-maven-3.9.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.9.3/bin:$PATH
  - mvn -v
  - sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  #- sudo apt-get update
  - sudo apt-get install -y --allow-unauthenticated r-base r-base-dev r-base-core r-recommended r-cran-rjava
  - sudo R CMD javareconf
  - sudo Rscript ./setup.R
  - ls -al ${R_HOME}

jobs:
  include:
    - script: "mvn -P ci install"
    - stage: deploy
      provider: script
      script: "mvn -P ci deploy -DskipTests"
      on:
        tags: true
        branches: true
